services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000" # Changement ici pour aligner le port hôte et conteneur
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_OUTPUT_WSS_PROXY=wss://app.cestpeutetrepasdesrumeurs.space/_next/webpack-hmr
    depends_on:
      - backend
    networks:
      - hackathon-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - hackathon-network

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - hackathon-network

volumes:
  db_data:

networks:
  hackathon-network:
    driver: bridge
