import type { ProductOffer } from "../api/types";

export const titleOffersMock: ProductOffer[] = [
  {
    id: "offer-navigo-annuel",
    slug: "navigo-annuel",
    name: "Forfait Navigo Annuel",
    productType: "NAVIGO_ANNUAL",
    shortDescription: "Voyager en illimité toute l'année.",
    longDescription: "Une offre annuelle pour les trajets quotidiens en Île-de-France.",
    priceLabel: "90,80 € / mois",
    durationLabel: "Annuel",
    targetProfile: "ADULT",
    minAge: null,
    maxAge: null,
    benefits: [
      { id: "benefit-annuel-1", label: "Idéal pour les trajets quotidiens" },
      { id: "benefit-annuel-2", label: "Transports illimités" },
      { id: "benefit-annuel-3", label: "Remboursement employeur possible" },
    ],
    requiredDocuments: [
      { id: "doc-annuel-1", documentType: "ID_DOCUMENT", label: "Pièce d'identité", required: true },
      { id: "doc-annuel-2", documentType: "PAYMENT_METHOD", label: "Moyen de paiement", required: true },
    ],
  },
  {
    id: "offer-junior",
    slug: "imagine-r-junior",
    name: "Imagine R Junior",
    productType: "IMAGINE_R_JUNIOR",
    shortDescription: "Le forfait annuel des enfants de moins de 11 ans.",
    longDescription: "Une offre très avantageuse pour les plus jeunes.",
    priceLabel: "25,20 € / an",
    durationLabel: "Annuel",
    targetProfile: "CHILD",
    minAge: null,
    maxAge: 10,
    benefits: [{ id: "benefit-junior-1", label: "Adapté aux moins de 11 ans" }],
    requiredDocuments: [{ id: "doc-junior-1", documentType: "PHOTO", label: "Photo récente", required: true }],
  },
  {
    id: "offer-scolaire",
    slug: "imagine-r-scolaire",
    name: "Imagine R Scolaire",
    productType: "IMAGINE_R_SCHOOL",
    shortDescription: "Le forfait annuel des jeunes scolarisés.",
    longDescription: "Une offre adaptée aux collégiens, lycéens et apprentis.",
    priceLabel: "401,30 € / an",
    durationLabel: "Annuel",
    targetProfile: "YOUNG",
    minAge: 11,
    maxAge: null,
    benefits: [{ id: "benefit-scolaire-1", label: "Renouvellement anticipable avant la rentrée" }],
    requiredDocuments: [
      { id: "doc-scolaire-1", documentType: "PHOTO", label: "Photo récente", required: true },
      { id: "doc-scolaire-2", documentType: "SCHOOL_CERTIFICATE", label: "Certificat scolaire", required: true },
    ],
  },
  {
    id: "offer-etudiant",
    slug: "imagine-r-etudiant",
    name: "Imagine R Étudiant",
    productType: "IMAGINE_R_STUDENT",
    shortDescription: "Le forfait annuel des étudiants.",
    longDescription: "Une offre post-bac visible dans le MVP.",
    priceLabel: "401,30 € / an",
    durationLabel: "Annuel",
    targetProfile: "STUDENT",
    minAge: null,
    maxAge: null,
    benefits: [{ id: "benefit-etudiant-1", label: "Adapté aux étudiants" }],
    requiredDocuments: [
      { id: "doc-etudiant-1", documentType: "PHOTO", label: "Photo récente", required: true },
      { id: "doc-etudiant-2", documentType: "SCHOOL_CERTIFICATE", label: "Certificat de scolarité", required: true },
    ],
  },
  {
    id: "offer-senior",
    slug: "navigo-senior",
    name: "Navigo Senior",
    productType: "NAVIGO_SENIOR",
    shortDescription: "Une offre à vérifier pour les seniors.",
    longDescription: "Un accompagnement pour préparer une offre senior.",
    priceLabel: "Tarif réduit à vérifier",
    durationLabel: "Annuel ou mensuel",
    targetProfile: "SENIOR",
    minAge: 62,
    maxAge: null,
    benefits: [{ id: "benefit-senior-1", label: "Accompagnement simplifié" }],
    requiredDocuments: [{ id: "doc-senior-1", documentType: "ID_DOCUMENT", label: "Pièce d'identité", required: true }],
  },
  {
    id: "offer-amethyste",
    slug: "amethyste",
    name: "Améthyste",
    productType: "AMETHYSTE",
    shortDescription: "Une offre solidaire selon département et situation.",
    longDescription: "Une orientation accompagnée pour vérifier les droits.",
    priceLabel: "Selon département",
    durationLabel: "Selon droits",
    targetProfile: "SENIOR",
    minAge: null,
    maxAge: null,
    benefits: [{ id: "benefit-amethyste-1", label: "Vérification accompagnée" }],
    requiredDocuments: [
      { id: "doc-amethyste-1", documentType: "ID_DOCUMENT", label: "Pièce d'identité", required: true },
      { id: "doc-amethyste-2", documentType: "SITUATION_PROOF", label: "Justificatif de situation", required: true },
    ],
  },
  {
    id: "offer-liberte",
    slug: "navigo-liberte-plus",
    name: "Navigo Liberté+",
    productType: "NAVIGO_LIBERTE",
    shortDescription: "Le paiement à l'usage pour les trajets occasionnels.",
    longDescription: "Une offre complémentaire sans abonnement mensuel.",
    priceLabel: "Dès 1,64 € / trajet",
    durationLabel: "À l'usage",
    targetProfile: "ADULT",
    minAge: null,
    maxAge: null,
    benefits: [{ id: "benefit-liberte-1", label: "Paiement à l'usage" }],
    requiredDocuments: [{ id: "doc-liberte-1", documentType: "PAYMENT_METHOD", label: "Moyen de paiement", required: true }],
  },
];
